/**
 * Official Georgian wine-traceability form templates — Annexes №1–№20.
 *
 * Titles, annex numbers, column headers and ordering are transcribed verbatim
 * from the official forms in docs/georgian-annexes-source.txt (დანართები.pdf).
 * Do NOT alter Georgian headers or column order without an updated source PDF;
 * bump `version` when the legal form changes.
 *
 * (The provided PDF contains №1–№20 only; there is no Annex №21, so none is
 * defined here.)
 */

import type { FormTemplate } from './types';

const SOURCE = 'დანართები.pdf — ტექნოლოგიური პროცესების აღრიცხვისა და შეტყობინების წესი';
const VERSION = '2024.1';

// Company-identity header block shared by every "notification" (შეტყობინება) form.
const companyHeader = [
  { key: 'companyName', labelKa: 'ღვინის კომპანიის დასახელება', labelEn: 'Company name', source: 'companyName' as const },
  { key: 'legalAddress', labelKa: 'ღვინის კომპანიის იურიდიული მისამართი', labelEn: 'Legal address', source: 'legalAddress' as const },
  { key: 'factualAddress', labelKa: 'ღვინის კომპანიის ფაქტობრივი მისამართი', labelEn: 'Factual address', source: 'factualAddress' as const },
  { key: 'idCode', labelKa: 'ღვინის კომპანიის საიდენტიფიკაციო კოდი', labelEn: 'Identification code', source: 'idCode' as const },
];

export const FORM_TEMPLATES: FormTemplate[] = [
  // ───────────────────────── Annex №1 — Vineyard journal ─────────────────────
  {
    id: 'annex_01_vineyard_journal',
    annexNumber: 1,
    titleKa: 'ვენახის აღრიცხვის ჟურნალი',
    titleEn: 'Vineyard accounting journal',
    category: 'vineyard',
    orientation: 'landscape',
    version: VERSION,
    sourceDoc: SOURCE,
    filters: ['accountingYear', 'vineyardBlock'],
    dataSource: 'blocks',
    headerFields: [
      { key: 'accountingYear', labelKa: 'სააღრიცხვო წელი', labelEn: 'Accounting year', source: 'accountingYear' },
    ],
    columns: [
      { key: 'parcelCadastral', headerKa: 'ნაკვეთის ს/კ', headerEn: 'Parcel cadastral code' },
      { key: 'municipality', headerKa: 'მუნიციპალიტეტი', headerEn: 'Municipality', group: 'ვენახის ადგილმდებარეობა', groupEn: 'Vineyard location' },
      { key: 'community', headerKa: 'თემი', headerEn: 'Community', group: 'ვენახის ადგილმდებარეობა', groupEn: 'Vineyard location' },
      { key: 'village', headerKa: 'სოფელი', headerEn: 'Village', group: 'ვენახის ადგილმდებარეობა', groupEn: 'Vineyard location' },
      { key: 'parcelName', headerKa: 'ნაკვეთის სახელი', headerEn: 'Parcel name', group: 'ვენახის ადგილმდებარეობა', groupEn: 'Vineyard location' },
      { key: 'variety', headerKa: 'ვაზის ჯიში', headerEn: 'Grape variety' },
      { key: 'areaSqm', headerKa: 'ფართობი კვ.მ.', headerEn: 'Area (sq.m)', numeric: true, total: true },
      { key: 'plantingYear', headerKa: 'გაშენების წელი', headerEn: 'Planting year' },
      { key: 'rootstock', headerKa: 'საძირე', headerEn: 'Rootstock' },
      { key: 'rowDistance', headerKa: 'მანძილი რიგთა შორის (მეტრი)', headerEn: 'Row spacing (m)', numeric: true },
      { key: 'vineDistance', headerKa: 'მანძილი ვაზთა შორის (მეტრი)', headerEn: 'Vine spacing (m)', numeric: true },
      { key: 'irrigation', headerKa: 'რწყვის არსებობა', headerEn: 'Irrigation present' },
      { key: 'condition', headerKa: 'ვენახის მდგომარეობა', headerEn: 'Vineyard condition' },
    ],
    totals: ['areaSqm'],
    signatureLabelKa: 'ხელმომწერი პირი:',
    filenameSlug: 'vineyard_journal',
  },

  // ───────────────────────── Annex №2 — Harvest journal ──────────────────────
  {
    id: 'annex_02_harvest_journal',
    annexNumber: 2,
    titleKa: 'რთველის ჟურნალი',
    titleEn: 'Harvest journal',
    category: 'harvest',
    orientation: 'landscape',
    version: VERSION,
    sourceDoc: SOURCE,
    filters: ['dateRange', 'vineyardBlock'],
    dataSource: 'harvests',
    headerFields: [
      { key: 'companyName', labelKa: 'ღვინის კომპანიის დასახელება', labelEn: 'Company name', source: 'companyName' },
    ],
    columns: [
      { key: 'date', headerKa: 'თარიღი', headerEn: 'Date' },
      { key: 'parcelName', headerKa: 'ნაკვეთის დასახელება', headerEn: 'Parcel name' },
      { key: 'variety', headerKa: 'ვაზის ჯიში', headerEn: 'Grape variety' },
      { key: 'areaHa', headerKa: 'დაკრეფილი ვენახის ფართი, ჰა', headerEn: 'Harvested area (ha)', numeric: true, total: true },
      { key: 'tons', headerKa: 'დაკრეფილი ყურძნის რაოდენობა, ტონა', headerEn: 'Grapes harvested (t)', numeric: true, total: true },
      { key: 'yieldPerHa', headerKa: 'საშუალო საჰექტარო მოსავალი, ტ/ჰა', headerEn: 'Avg yield (t/ha)', numeric: true },
      { key: 'note', headerKa: 'შენიშვნა', headerEn: 'Note' },
    ],
    totals: ['areaHa', 'tons'],
    signatureLabelKa: 'ხელმომწერი პირი:',
    filenameSlug: 'harvest_journal',
  },

  // ──────────────────────── Annex №3 — Grape reception ───────────────────────
  {
    id: 'annex_03_grape_reception',
    annexNumber: 3,
    titleKa: 'ყურძნის მიღების ჟურნალი',
    titleEn: 'Grape reception journal',
    category: 'harvest',
    orientation: 'landscape',
    version: VERSION,
    sourceDoc: SOURCE,
    filters: ['dateRange', 'vineyardBlock'],
    dataSource: 'grapeReception',
    headerFields: [
      { key: 'processingPlace', labelKa: 'ყურძნის გადამუშავების ადგილი', labelEn: 'Grape processing place', source: 'wineryName' },
    ],
    columns: [
      { key: 'no', headerKa: '№', headerEn: 'No.' },
      { key: 'date', headerKa: 'მიღების თარიღი', headerEn: 'Reception date' },
      { key: 'supplier', headerKa: 'მომწოდებელი', headerEn: 'Supplier' },
      { key: 'variety', headerKa: 'ყურძნის ჯიში', headerEn: 'Grape variety' },
      { key: 'location', headerKa: 'ვენახის ადგილმდებარეობა', headerEn: 'Vineyard location' },
      { key: 'transport', headerKa: 'ტრანსპორტის დასახელება №', headerEn: 'Transport / №' },
      { key: 'brutto', headerKa: 'ბრუტო კგ', headerEn: 'Gross (kg)', group: 'ყურძნის რაოდენობა, კგ', groupEn: 'Grape quantity (kg)', numeric: true, total: true },
      { key: 'tara', headerKa: 'ტარა კგ', headerEn: 'Tare (kg)', group: 'ყურძნის რაოდენობა, კგ', groupEn: 'Grape quantity (kg)', numeric: true, total: true },
      { key: 'netto', headerKa: 'ნეტო კგ', headerEn: 'Net (kg)', group: 'ყურძნის რაოდენობა, კგ', groupEn: 'Grape quantity (kg)', numeric: true, total: true },
      { key: 'analysisNo', headerKa: 'ანალიზი №', headerEn: 'Analysis №' },
      { key: 'sugar', headerKa: 'შაქრიანობა %', headerEn: 'Sugar %', numeric: true },
      { key: 'note', headerKa: 'შენიშვნა', headerEn: 'Note' },
    ],
    totals: ['brutto', 'tara', 'netto'],
    signatureLabelKa: 'ხელმომწერი პირი:',
    filenameSlug: 'grape_reception',
  },

  // ──────────────────── Annex №4 — Wine movement journal ─────────────────────
  {
    id: 'annex_04_wine_movement',
    annexNumber: 4,
    titleKa: 'ღვინის ბრუნვის აღრიცხვის ჟურნალი',
    titleEn: 'Wine movement / turnover journal',
    category: 'cellar',
    orientation: 'portrait',
    version: VERSION,
    sourceDoc: SOURCE,
    filters: ['dateRange', 'wineLot', 'tank'],
    dataSource: 'wineMovements',
    headerFields: [
      { key: 'product', labelKa: 'პროდუქციის დასახელება, ტიპი, კატეგორია', labelEn: 'Product, type, category', source: 'product' },
      { key: 'vintage', labelKa: 'მოსავლის წელი (ასაკი): (დალ)', labelEn: 'Vintage (age): (dal)', source: 'input' },
    ],
    columns: [
      { key: 'date', headerKa: 'თარიღი', headerEn: 'Date' },
      { key: 'fromTo', headerKa: 'საიდან შემოვიდა, სად გაიგზავნა', headerEn: 'From / to' },
      { key: 'incoming', headerKa: 'შემოსავალი', headerEn: 'Incoming', numeric: true, total: true },
      { key: 'outgoing', headerKa: 'გასავალი', headerEn: 'Outgoing', numeric: true, total: true },
      { key: 'balance', headerKa: 'ნაშთი', headerEn: 'Balance', numeric: true },
      { key: 'note', headerKa: 'შენიშვნა', headerEn: 'Note' },
    ],
    totals: ['incoming', 'outgoing'],
    hasRunningBalance: true,
    signatureLabelKa: 'ხელმომწერი პირი:',
    filenameSlug: 'wine_movement_journal',
  },

  // ────────────────────────── Annex №5 — Wine aging act ──────────────────────
  {
    id: 'annex_05_wine_aging_act',
    annexNumber: 5,
    titleKa: 'ღვინის დავარგებაზე ჩაყენების აქტი №',
    titleEn: 'Wine aging (placement) act',
    category: 'cellar',
    orientation: 'landscape',
    version: VERSION,
    sourceDoc: SOURCE,
    filters: ['dateRange', 'wineLot', 'tank'],
    dataSource: 'wineAging',
    headerFields: [
      { key: 'wineName', labelKa: 'ღვინის დასახელება', labelEn: 'Wine name', source: 'product' },
      { key: 'vintage', labelKa: 'მოსავლის წელი', labelEn: 'Vintage', source: 'input' },
      { key: 'color', labelKa: 'ფერი', labelEn: 'Colour', source: 'input' },
      { key: 'type', labelKa: 'ტიპი', labelEn: 'Type', source: 'input' },
      { key: 'category', labelKa: 'კატეგორია', labelEn: 'Category', source: 'input' },
    ],
    columns: [
      { key: 'placeDate', headerKa: 'დავარგებაზე ჩაყენების თარიღი', headerEn: 'Placement date', group: 'დავარგებაზე ჩაყენება', groupEn: 'Placed for aging' },
      { key: 'vesselNo', headerKa: 'ჭურჭელი/კასრები №', headerEn: 'Vessel/barrel №', group: 'დავარგებაზე ჩაყენება', groupEn: 'Placed for aging' },
      { key: 'placeQty', headerKa: 'რაოდენობა (დალ)', headerEn: 'Quantity (dal)', group: 'დავარგებაზე ჩაყენება', groupEn: 'Placed for aging', numeric: true, total: true },
      { key: 'placeAlc', headerKa: 'სპირტშემცველობა %', headerEn: 'Alcohol %', group: 'დავარგებაზე ჩაყენება', groupEn: 'Placed for aging', numeric: true },
      { key: 'placeSugar', headerKa: 'შაქრიანობა გ/ლ', headerEn: 'Sugar g/L', group: 'დავარგებაზე ჩაყენება', groupEn: 'Placed for aging', numeric: true },
      { key: 'placeAcid', headerKa: 'ტიტრული მჟავიანობა გ/ლ', headerEn: 'Titratable acidity g/L', group: 'დავარგებაზე ჩაყენება', groupEn: 'Placed for aging', numeric: true },
      { key: 'removeDate', headerKa: 'მოხსნის თარიღი', headerEn: 'Removal date', group: 'დავარგებიდან მოხსნა', groupEn: 'Removed from aging' },
      { key: 'removeQty', headerKa: 'რაოდენობა (დალ)', headerEn: 'Quantity (dal)', group: 'დავარგებიდან მოხსნა', groupEn: 'Removed from aging', numeric: true },
      { key: 'removeAlc', headerKa: 'სპირტშემცველობა %', headerEn: 'Alcohol %', group: 'დავარგებიდან მოხსნა', groupEn: 'Removed from aging', numeric: true },
      { key: 'removeSugar', headerKa: 'შაქრიანობა გ/ლ', headerEn: 'Sugar g/L', group: 'დავარგებიდან მოხსნა', groupEn: 'Removed from aging', numeric: true },
      { key: 'removeAcid', headerKa: 'ტიტრული მჟავიანობა გ/ლ', headerEn: 'Titratable acidity g/L', group: 'დავარგებიდან მოხსნა', groupEn: 'Removed from aging', numeric: true },
      { key: 'balance', headerKa: 'ნაშთი (დალ)', headerEn: 'Balance (dal)', numeric: true },
    ],
    totals: ['placeQty'],
    signatureLabelKa: 'ხელმომწერი პირი:',
    filenameSlug: 'wine_aging_act',
  },

  // ───────────────────────── Annex №6 — Wine blending act ────────────────────
  {
    id: 'annex_06_wine_blending_act',
    annexNumber: 6,
    titleKa: 'ღვინის კუპაჟის აქტი №',
    titleEn: 'Wine blending (coupage) act',
    category: 'cellar',
    orientation: 'landscape',
    version: VERSION,
    sourceDoc: SOURCE,
    filters: ['dateRange', 'wineLot', 'tank'],
    dataSource: 'wineBlending',
    headerFields: [
      { key: 'wineName', labelKa: 'ღვინის დასახელება', labelEn: 'Wine name', source: 'product' },
      { key: 'date', labelKa: 'რიცხვი / თვე / წელი', labelEn: 'Date', source: 'dateRange' },
      { key: 'blendTank', labelKa: 'საკუპაჟე ცისტერნის №', labelEn: 'Blending tank №', source: 'input' },
    ],
    columns: [
      { key: 'no', headerKa: '№', headerEn: 'No.' },
      { key: 'material', headerKa: 'კუპაჟში მონაწილე ნედლეულისა და მასალების დასახელება', headerEn: 'Blend component' },
      { key: 'qty', headerKa: 'რაოდენობა (დალ)', headerEn: 'Quantity (dal)', numeric: true, total: true },
      { key: 'analysisNo', headerKa: 'ანალიზის №', headerEn: 'Analysis №' },
      { key: 'alc', headerKa: 'შემცველობა %', headerEn: 'Alcohol content %', numeric: true },
      { key: 'sugar', headerKa: 'შაქრიანობა %', headerEn: 'Sugar %', numeric: true },
      { key: 'spirit', headerKa: 'სპირტი (3×5)', headerEn: 'Spirit (3×5)', numeric: true, total: true },
      { key: 'sugarTotal', headerKa: 'შაქარი (3×6)', headerEn: 'Sugar (3×6)', numeric: true, total: true },
      { key: 'note', headerKa: 'შენიშვნა', headerEn: 'Note' },
    ],
    totals: ['qty', 'spirit', 'sugarTotal'],
    signatureLabelKa: 'ხელმომწერი პირი:',
    filenameSlug: 'wine_blending_act',
  },

  // ──────────────────────────── Annex №7 — Bottling act ──────────────────────
  {
    id: 'annex_07_bottling_act',
    annexNumber: 7,
    titleKa: 'ჩამოსხმის აქტი №',
    titleEn: 'Bottling act',
    category: 'bottling',
    orientation: 'landscape',
    version: VERSION,
    sourceDoc: SOURCE,
    filters: ['dateRange', 'wineLot'],
    dataSource: 'bottling',
    headerFields: [
      { key: 'product', labelKa: 'პროდუქტის დასახელება', labelEn: 'Product name', source: 'product' },
    ],
    columns: [
      { key: 'wineNo', headerKa: 'ღვინის ან კუპაჟის №', headerEn: 'Wine/blend №' },
      { key: 'lotNo', headerKa: 'ლოტის №', headerEn: 'Lot №' },
      { key: 'inDate', headerKa: 'შემოვიდა თარიღი', headerEn: 'Received date', group: 'შემოვიდა წარმოებიდან', groupEn: 'Received from production' },
      { key: 'inQty', headerKa: 'რაოდენობა (დალ)', headerEn: 'Quantity (dal)', group: 'შემოვიდა წარმოებიდან', groupEn: 'Received from production', numeric: true, total: true },
      { key: 'fillDate', headerKa: 'ჩამოისხა თარიღი', headerEn: 'Bottled date', group: 'ჩამოისხა', groupEn: 'Bottled' },
      { key: 'fillQty', headerKa: 'რაოდენობა (დალ)', headerEn: 'Quantity (dal)', group: 'ჩამოისხა', groupEn: 'Bottled', numeric: true, total: true },
      { key: 'bottles', headerKa: 'ბოთლი (ცალი)', headerEn: 'Bottles (pcs)', group: 'ჩამოისხა', groupEn: 'Bottled', numeric: true, total: true },
      { key: 'ceramic', headerKa: 'კერამიკა (ცალი)', headerEn: 'Ceramic (pcs)', group: 'ჩამოისხა', groupEn: 'Bottled', numeric: true, total: true },
      { key: 'note', headerKa: 'შენიშვნა', headerEn: 'Note' },
    ],
    totals: ['inQty', 'fillQty', 'bottles', 'ceramic'],
    signatureLabelKa: 'ხელმომწერი პირი:',
    filenameSlug: 'bottling_act',
    notes: 'ბოთლის ფორმატების (0.75/0.5/0.2/1.5/3.0/0.375 ლ) დაშლა აპლიკაციაში არ აღირიცხება — იხ. TODO mapper-ში.',
  },

  // ─────────────────── Annex №8 — Finished goods warehouse ───────────────────
  {
    id: 'annex_08_warehouse_movement',
    annexNumber: 8,
    titleKa: 'მზა ნაწარმის საწყობში პროდუქციის მოძრაობის ჟურნალი',
    titleEn: 'Finished goods warehouse movement journal',
    category: 'warehouse',
    orientation: 'landscape',
    version: VERSION,
    sourceDoc: SOURCE,
    filters: ['dateRange', 'wineLot', 'warehouse'],
    dataSource: 'warehouse',
    headerFields: [
      { key: 'wineName', labelKa: 'ღვინის დასახელება', labelEn: 'Wine name', source: 'product' },
      { key: 'lotNo', labelKa: 'ლოტის №', labelEn: 'Lot №', source: 'input' },
    ],
    columns: [
      { key: 'date', headerKa: 'თარიღი', headerEn: 'Date', group: 'გაფორმებული', groupEn: 'Documented' },
      { key: 'fromTo', headerKa: 'საიდან, სად', headerEn: 'From / to', group: 'გაფორმებული', groupEn: 'Documented' },
      { key: 'incoming', headerKa: 'შემოსავალი', headerEn: 'Incoming', group: 'გაფორმებული', groupEn: 'Documented', numeric: true, total: true },
      { key: 'outgoing', headerKa: 'გასავალი', headerEn: 'Outgoing', group: 'გაფორმებული', groupEn: 'Documented', numeric: true, total: true },
      { key: 'balance', headerKa: 'ნაშთი', headerEn: 'Balance', group: 'გაფორმებული', groupEn: 'Documented', numeric: true },
    ],
    totals: ['incoming', 'outgoing'],
    hasRunningBalance: true,
    signatureLabelKa: 'ხელმომწერი პირი:',
    filenameSlug: 'warehouse_movement',
  },

  // ──────────────────────────── Annex №9 — Distillation ──────────────────────
  {
    id: 'annex_09_distillation_act',
    annexNumber: 9,
    titleKa: 'გამოხდის აქტი №',
    titleEn: 'Distillation act',
    category: 'distillation',
    orientation: 'landscape',
    version: VERSION,
    sourceDoc: SOURCE,
    filters: ['dateRange'],
    dataSource: '',
    headerFields: [
      { key: 'companyName', labelKa: 'კომპანიის დასახელება', labelEn: 'Company name', source: 'companyName' },
      { key: 'date', labelKa: 'თარიღი', labelEn: 'Date', source: 'dateRange' },
    ],
    columns: [
      { key: 'no', headerKa: '№', headerEn: 'No.' },
      { key: 'rawName', headerKa: 'დასახელება', headerEn: 'Name', group: 'ნედლეული', groupEn: 'Raw material' },
      { key: 'rawQtyDal', headerKa: 'რაოდენობა დალ', headerEn: 'Quantity (dal)', group: 'ნედლეული', groupEn: 'Raw material', numeric: true, total: true },
      { key: 'rawAlc', headerKa: 'სპირტშემცველობა %', headerEn: 'Alcohol %', group: 'ნედლეული', groupEn: 'Raw material', numeric: true },
      { key: 'rawQtyAa', headerKa: 'რაოდენობა ა.ა', headerEn: 'Quantity (a.a.)', group: 'ნედლეული', groupEn: 'Raw material', numeric: true, total: true },
      { key: 'prodName', headerKa: 'დასახელება', headerEn: 'Name', group: 'მიღებული პროდუქტი', groupEn: 'Obtained product' },
      { key: 'prodQtyDal', headerKa: 'რაოდენობა დალ', headerEn: 'Quantity (dal)', group: 'მიღებული პროდუქტი', groupEn: 'Obtained product', numeric: true, total: true },
      { key: 'prodAlc', headerKa: 'სპირტშემცველობა %', headerEn: 'Alcohol %', group: 'მიღებული პროდუქტი', groupEn: 'Obtained product', numeric: true },
      { key: 'prodQtyAa', headerKa: 'რაოდენობა ა.ა', headerEn: 'Quantity (a.a.)', group: 'მიღებული პროდუქტი', groupEn: 'Obtained product', numeric: true, total: true },
      { key: 'note', headerKa: 'შენიშვნა', headerEn: 'Note' },
    ],
    totals: ['rawQtyDal', 'rawQtyAa', 'prodQtyDal', 'prodQtyAa'],
    signatureLabelKa: 'ხელმომწერი პირი:',
    filenameSlug: 'distillation_act',
    notes: 'აპლიკაცია ჯერ არ აღრიცხავs ხდის (distillation) ოპერაციებს — ცარიელი/TODO.',
  },

  // ─────────────────── Annex №10 — Distillate aging act ──────────────────────
  {
    id: 'annex_10_distillate_aging',
    annexNumber: 10,
    titleKa: 'ღვინის (ჭაჭის) დისტილატის დავარგებაზე ჩაყენების აქტი №',
    titleEn: 'Wine (pomace) distillate aging act',
    category: 'distillation',
    orientation: 'landscape',
    version: VERSION,
    sourceDoc: SOURCE,
    filters: ['dateRange'],
    dataSource: '',
    headerFields: [
      { key: 'companyName', labelKa: 'კომპანიის დასახელება', labelEn: 'Company name', source: 'companyName' },
      { key: 'distillateName', labelKa: 'დისტილატის დასახელება', labelEn: 'Distillate name', source: 'input' },
      { key: 'barrelCount', labelKa: 'კასრების რაოდენობა', labelEn: 'Barrel count', source: 'input' },
      { key: 'stackNo', labelKa: 'შტაბელის №', labelEn: 'Stack №', source: 'input' },
      { key: 'tankNo', labelKa: 'ცისტერნის №', labelEn: 'Tank №', source: 'input' },
      { key: 'tankCapacity', labelKa: 'ცისტერნის ტევადობა', labelEn: 'Tank capacity', source: 'input' },
      { key: 'chipVolume', labelKa: 'ტკეჩის მოცულობა', labelEn: 'Chips volume', source: 'input' },
    ],
    columns: [
      { key: 'placeDate', headerKa: 'ჩაყენების თარიღი', headerEn: 'Placement date', group: 'დისტილატის ჩაყენება დავარგებაზე', groupEn: 'Distillate placed' },
      { key: 'placeQtyDal', headerKa: 'რაოდენობა დალ', headerEn: 'Quantity (dal)', group: 'დისტილატის ჩაყენება დავარგებაზე', groupEn: 'Distillate placed', numeric: true, total: true },
      { key: 'placeStrength', headerKa: 'სიმაგრე %', headerEn: 'Strength %', group: 'დისტილატის ჩაყენება დავარგებაზე', groupEn: 'Distillate placed', numeric: true },
      { key: 'placeFactor', headerKa: 'მამრავლი V-ცხრ.', headerEn: 'Factor V', group: 'დისტილატის ჩაყენება დავარგებაზე', groupEn: 'Distillate placed', numeric: true },
      { key: 'placeQtyAa', headerKa: 'რაოდენობა ა/ა', headerEn: 'Quantity (a.a.)', group: 'დისტილატის ჩაყენება დავარგებაზე', groupEn: 'Distillate placed', numeric: true, total: true },
      { key: 'removeDate', headerKa: 'მოხსნის თარიღი/№', headerEn: 'Removal date/№', group: 'დისტილატის მოხსნა დავარგებიდან', groupEn: 'Distillate removed' },
      { key: 'removeQtyDal', headerKa: 'რაოდენობა დალ', headerEn: 'Quantity (dal)', group: 'დისტილატის მოხსნა დავარგებიდან', groupEn: 'Distillate removed', numeric: true },
      { key: 'removeAge', headerKa: 'დავარგების ასაკი/წელი', headerEn: 'Aging age/year', group: 'დისტილატის მოხსნა დავარგებიდან', groupEn: 'Distillate removed' },
      { key: 'removeStrength', headerKa: 'სიმაგრე %', headerEn: 'Strength %', group: 'დისტილატის მოხსნა დავარგებიდან', groupEn: 'Distillate removed', numeric: true },
      { key: 'removeFactor', headerKa: 'მამრავლი V-ცხრ.', headerEn: 'Factor V', group: 'დისტილატის მოხსნა დავარგებიდან', groupEn: 'Distillate removed', numeric: true },
      { key: 'removeQtyAa', headerKa: 'რაოდენობა ა/ა', headerEn: 'Quantity (a.a.)', group: 'დისტილატის მოხსნა დავარგებიდან', groupEn: 'Distillate removed', numeric: true },
      { key: 'balanceDal', headerKa: 'ნაშთი დალ', headerEn: 'Balance (dal)', numeric: true },
      { key: 'balanceAa', headerKa: 'ნაშთი ა/ა', headerEn: 'Balance (a.a.)', numeric: true },
    ],
    totals: ['placeQtyDal', 'placeQtyAa'],
    signatureLabelKa: 'ხელმომწერი პირი:',
    filenameSlug: 'distillate_aging_act',
    notes: 'აპლიკაცია ჯერ არ აღრიცხავს დისტილატის დავარგებას — ცარიელი/TODO.',
  },

  // ───────────────── Annex №11 — Spirit beverage blending act ────────────────
  {
    id: 'annex_11_spirit_blending',
    annexNumber: 11,
    titleKa: 'სპირტიანი სასმელების კუპაჟის აქტი №',
    titleEn: 'Spirit beverage blending act',
    category: 'distillation',
    orientation: 'landscape',
    version: VERSION,
    sourceDoc: SOURCE,
    filters: ['dateRange'],
    dataSource: '',
    headerFields: [
      { key: 'beverageName', labelKa: 'სასმელის დასახელება', labelEn: 'Beverage name', source: 'product' },
      { key: 'date', labelKa: 'თარიღი', labelEn: 'Date', source: 'dateRange' },
    ],
    columns: [
      { key: 'no', headerKa: '№', headerEn: 'No.' },
      { key: 'material', headerKa: 'კუპაჟში მონაწილე მასალები', headerEn: 'Blend components' },
      { key: 'age', headerKa: 'დისტილატის ასაკი/წელი', headerEn: 'Distillate age/year' },
      { key: 'qtyDal', headerKa: 'რაოდენობა (დალ)', headerEn: 'Quantity (dal)', numeric: true, total: true },
      { key: 'alc', headerKa: 'სპირტშემცველობა %', headerEn: 'Alcohol %', group: 'ალკოჰოლი', groupEn: 'Alcohol', numeric: true },
      { key: 'aaContent', headerKa: 'ა.ა-ის შემცველობა (დალ)', headerEn: 'a.a. content (dal)', group: 'ალკოჰოლი', groupEn: 'Alcohol', numeric: true, total: true },
      { key: 'sugarPct', headerKa: 'შაქრიანობა %', headerEn: 'Sugar %', group: 'შაქარი', groupEn: 'Sugar', numeric: true },
      { key: 'sugar', headerKa: 'შაქარი (4×7)', headerEn: 'Sugar (4×7)', group: 'შაქარი', groupEn: 'Sugar', numeric: true, total: true },
      { key: 'sugarCost', headerKa: 'შაქრის ხარჯი კგ', headerEn: 'Sugar used (kg)', group: 'შაქარი', groupEn: 'Sugar', numeric: true, total: true },
    ],
    totals: ['qtyDal', 'aaContent', 'sugar', 'sugarCost'],
    signatureLabelKa: 'ხელმომწერი პირი:',
    filenameSlug: 'spirit_blending_act',
    notes: 'აპლიკაცია ჯერ არ აღრიცხავს სპირტიან სასმელებს — ცარიელი/TODO.',
  },

  // ─────────────────── Annex №12 — Distillate movement ───────────────────────
  {
    id: 'annex_12_distillate_movement',
    annexNumber: 12,
    titleKa: 'დისტილატების, ყურძნისეული წარმოშობის სპირტისა და სპირტიანი სასმელის ბრუნვისა და ნაშთების რეგისტრაციის ჟურნალი',
    titleEn: 'Distillate / grape spirit / spirit beverage movement journal',
    category: 'distillation',
    orientation: 'landscape',
    version: VERSION,
    sourceDoc: SOURCE,
    filters: ['dateRange', 'product'],
    dataSource: '',
    headerFields: [
      { key: 'product', labelKa: 'პროდუქციის დასახელება, ტიპი, კატეგორია', labelEn: 'Product, type, category', source: 'product' },
      { key: 'age', labelKa: 'ასაკი', labelEn: 'Age', source: 'input' },
    ],
    columns: [
      { key: 'date', headerKa: 'თარიღი', headerEn: 'Date' },
      { key: 'fromTo', headerKa: 'საიდან, სად', headerEn: 'From / to' },
      { key: 'inDal', headerKa: 'დალ', headerEn: 'dal', group: 'შემოსავალი', groupEn: 'Incoming', numeric: true, total: true },
      { key: 'inAa', headerKa: 'ა.ა.', headerEn: 'a.a.', group: 'შემოსავალი', groupEn: 'Incoming', numeric: true, total: true },
      { key: 'outDal', headerKa: 'დალ', headerEn: 'dal', group: 'გასავალი', groupEn: 'Outgoing', numeric: true, total: true },
      { key: 'outAa', headerKa: 'ა.ა', headerEn: 'a.a.', group: 'გასავალი', groupEn: 'Outgoing', numeric: true, total: true },
      { key: 'balDal', headerKa: 'დალ', headerEn: 'dal', group: 'ნაშთი', groupEn: 'Balance', numeric: true },
      { key: 'balAa', headerKa: 'ა.ა', headerEn: 'a.a.', group: 'ნაშთი', groupEn: 'Balance', numeric: true },
      { key: 'note', headerKa: 'შენიშვნა', headerEn: 'Note' },
    ],
    totals: ['inDal', 'inAa', 'outDal', 'outAa'],
    hasRunningBalance: true,
    signatureLabelKa: 'ხელმომწერი პირი:',
    filenameSlug: 'distillate_movement',
    notes: 'აპლიკაცია ჯერ არ აღრიცხავს დისტილატებს — ცარიელი/TODO.',
  },

  // ─────────────────── Annex №13 — Auxiliary materials ───────────────────────
  {
    id: 'annex_13_materials_movement',
    annexNumber: 13,
    titleKa: 'დამხმარე მასალების (საფუარი, საფუარის საკვები, ფერმენტი, ბენტონიტი, ჟელატინი და სხვა) ბრუნვის ჟურნალი',
    titleEn: 'Auxiliary materials movement journal',
    category: 'materials',
    orientation: 'portrait',
    version: VERSION,
    sourceDoc: SOURCE,
    filters: ['dateRange', 'material'],
    dataSource: 'materials',
    headerFields: [],
    columns: [
      { key: 'date', headerKa: 'თარიღი', headerEn: 'Date' },
      { key: 'docNo', headerKa: 'დოკუმენტის №', headerEn: 'Document №' },
      { key: 'fromTo', headerKa: 'საიდან შემოვიდა, სად გაიხარჯა', headerEn: 'From / used where' },
      { key: 'incoming', headerKa: 'შემოსავალი', headerEn: 'Incoming', group: 'მოძრაობა', groupEn: 'Movement', numeric: true, total: true },
      { key: 'outgoing', headerKa: 'გასავალი', headerEn: 'Outgoing', group: 'მოძრაობა', groupEn: 'Movement', numeric: true, total: true },
      { key: 'balance', headerKa: 'ნაშთი', headerEn: 'Balance', group: 'მოძრაობა', groupEn: 'Movement', numeric: true },
    ],
    totals: ['incoming', 'outgoing'],
    hasRunningBalance: true,
    signatureLabelKa: 'ხელმომწერი პირი:',
    filenameSlug: 'materials_movement',
  },

  // ──────────────────── Annex №14 — Concentrated must ────────────────────────
  {
    id: 'annex_14_concentrated_must',
    annexNumber: 14,
    titleKa: 'კონცენტრირებული ყურძნის ტკბილის ბრუნვა',
    titleEn: 'Concentrated grape must movement',
    category: 'materials',
    orientation: 'portrait',
    version: VERSION,
    sourceDoc: SOURCE,
    filters: ['dateRange'],
    dataSource: '',
    headerFields: [
      { key: 'unit', labelKa: 'ერთეული: (დალ)', labelEn: 'Unit: (dal)', source: 'input' },
    ],
    columns: [
      { key: 'date', headerKa: 'თარიღი', headerEn: 'Date' },
      { key: 'docNo', headerKa: 'საბუთები №', headerEn: 'Documents №' },
      { key: 'fromTo', headerKa: 'საიდან შემოვიდა, სად გაიხარჯა', headerEn: 'From / used where' },
      { key: 'incoming', headerKa: 'შემოსავალი', headerEn: 'Incoming', group: 'მოძრაობა', groupEn: 'Movement', numeric: true, total: true },
      { key: 'outgoing', headerKa: 'გასავალი', headerEn: 'Outgoing', group: 'მოძრაობა', groupEn: 'Movement', numeric: true, total: true },
      { key: 'balance', headerKa: 'ნაშთი', headerEn: 'Balance', group: 'მოძრაობა', groupEn: 'Movement', numeric: true },
    ],
    totals: ['incoming', 'outgoing'],
    hasRunningBalance: true,
    signatureLabelKa: 'ხელმომწერი პირი:',
    filenameSlug: 'concentrated_must',
    notes: 'აპლიკაცია ჯერ არ აღრიცხავს კონცენტრირებულ ტკბილს — ცარიელი/TODO.',
  },

  // ──────────────── Annex №15 — Grafting material notification ────────────────
  {
    id: 'annex_15_seedlings_notification',
    annexNumber: 15,
    titleKa: 'შეტყობინება ვაზის სამყნობი მასალებისა და ნამყენი ნერგის მოძრაობის შესახებ',
    titleEn: 'Notification on movement of grafting material and grafted seedlings',
    category: 'notification',
    orientation: 'portrait',
    version: VERSION,
    sourceDoc: SOURCE,
    filters: ['dateRange'],
    dataSource: '',
    headerFields: [
      ...companyHeader,
      { key: 'product', labelKa: 'პროდუქციის დასახელება', labelEn: 'Product name', source: 'product' },
      { key: 'variety', labelKa: 'ჯიში / ცალი', labelEn: 'Variety / pcs', source: 'input' },
    ],
    columns: [
      { key: 'date', headerKa: 'თარიღი', headerEn: 'Date' },
      { key: 'fromTo', headerKa: 'საიდან შემოვიდა, სად გაიგზავნა', headerEn: 'From / to' },
      { key: 'incoming', headerKa: 'შემოსავალი', headerEn: 'Incoming', numeric: true, total: true },
      { key: 'outgoing', headerKa: 'გასავალი', headerEn: 'Outgoing', numeric: true, total: true },
      { key: 'balance', headerKa: 'ნაშთი', headerEn: 'Balance', numeric: true },
      { key: 'note', headerKa: 'შენიშვნა', headerEn: 'Note' },
    ],
    totals: ['incoming', 'outgoing'],
    hasRunningBalance: true,
    signatureLabelKa: 'ხელმომწერი პირი:',
    filenameSlug: 'seedlings_notification',
    notes: 'აპლიკაცია ჯერ არ აღრიცხავს სანერგე მასალას — ცარიელი/TODO.',
  },

  // ───────────────────── Annex №16 — Vineyard notification ───────────────────
  {
    id: 'annex_16_vineyard_notification',
    annexNumber: 16,
    titleKa: 'შეტყობინება ვენახის შესახებ',
    titleEn: 'Notification about the vineyard',
    category: 'notification',
    orientation: 'landscape',
    version: VERSION,
    sourceDoc: SOURCE,
    filters: ['accountingYear', 'vineyardBlock'],
    dataSource: 'blocks',
    headerFields: [
      ...companyHeader,
      { key: 'accountingYear', labelKa: 'სააღრიცხვო წელი', labelEn: 'Accounting year', source: 'accountingYear' },
    ],
    columns: [
      { key: 'parcelCadastral', headerKa: 'ნაკვეთის ს/კ', headerEn: 'Parcel cadastral code' },
      { key: 'municipality', headerKa: 'მუნიციპალიტეტი', headerEn: 'Municipality', group: 'ვენახის ადგილმდებარეობა', groupEn: 'Vineyard location' },
      { key: 'community', headerKa: 'თემი', headerEn: 'Community', group: 'ვენახის ადგილმდებარეობა', groupEn: 'Vineyard location' },
      { key: 'village', headerKa: 'სოფელი', headerEn: 'Village', group: 'ვენახის ადგილმდებარეობა', groupEn: 'Vineyard location' },
      { key: 'parcelName', headerKa: 'ნაკვეთის სახელი', headerEn: 'Parcel name', group: 'ვენახის ადგილმდებარეობა', groupEn: 'Vineyard location' },
      { key: 'variety', headerKa: 'ვაზის ჯიში', headerEn: 'Grape variety' },
      { key: 'areaSqm', headerKa: 'ფართობი კვ.მ', headerEn: 'Area (sq.m)', numeric: true, total: true },
      { key: 'plantingYear', headerKa: 'გაშენების წელი', headerEn: 'Planting year' },
      { key: 'rootstock', headerKa: 'საძირე', headerEn: 'Rootstock' },
      { key: 'rowDistance', headerKa: 'მანძილი რიგთა შორის (მეტრი)', headerEn: 'Row spacing (m)', numeric: true },
      { key: 'vineDistance', headerKa: 'მანძილი ვაზთა შორის (მეტრი)', headerEn: 'Vine spacing (m)', numeric: true },
      { key: 'irrigation', headerKa: 'რწყვის არსებობა', headerEn: 'Irrigation present' },
      { key: 'condition', headerKa: 'ვენახის მდგომარეობა', headerEn: 'Vineyard condition' },
    ],
    totals: ['areaSqm'],
    signatureLabelKa: 'ხელმომწერი პირი:',
    filenameSlug: 'vineyard_notification',
  },

  // ────────────── Annex №17 — Grape processing notification ──────────────────
  {
    id: 'annex_17_processing_notification',
    annexNumber: 17,
    titleKa: 'შეტყობინება ყურძნის გადამუშავების შესახებ',
    titleEn: 'Notification about grape processing (season)',
    category: 'notification',
    orientation: 'landscape',
    version: VERSION,
    sourceDoc: SOURCE,
    filters: ['season'],
    dataSource: 'processingSummary',
    headerFields: [...companyHeader],
    columns: [
      { key: 'variety', headerKa: 'ყურძნის ჯიში', headerEn: 'Grape variety' },
      { key: 'grapeTons', headerKa: 'ყურძნის რაოდენობა ტონა', headerEn: 'Grapes (t)', numeric: true, total: true },
      { key: 'avgSugar', headerKa: 'საშუალო შაქარი %', headerEn: 'Avg sugar %', numeric: true },
      { key: 'wineCategory', headerKa: 'ღვინის კატეგორია შაქრიანობის მიხედვით', headerEn: 'Wine category by sugar' },
      { key: 'wineTotal', headerKa: 'ღვინო (ჯამი) დალ', headerEn: 'Wine total (dal)', numeric: true, total: true },
      { key: 'pdoWine', headerKa: 'ადგილწარმოშობის დასახელება დალ', headerEn: 'PDO wine (dal)', group: 'მათ შორის', groupEn: 'Of which', numeric: true, total: true },
      { key: 'pgiWine', headerKa: 'გეოგრაფიული აღნიშვნის დასახელება დალ', headerEn: 'PGI wine (dal)', group: 'მათ შორის', groupEn: 'Of which', numeric: true, total: true },
      { key: 'otherWine', headerKa: 'სხვა ღვინო (სუფრის) დალ', headerEn: 'Other (table) wine (dal)', group: 'მათ შორის', groupEn: 'Of which', numeric: true, total: true },
      { key: 'distillWine', headerKa: 'გამოსახდელი დალ', headerEn: 'For distillation (dal)', group: 'მათ შორის', groupEn: 'Of which', numeric: true, total: true },
    ],
    totals: ['grapeTons', 'wineTotal', 'pdoWine', 'pgiWine', 'otherWine', 'distillWine'],
    signatureLabelKa: 'ხელმომწერი პირი:',
    filenameSlug: 'processing_notification',
  },

  // ──────────────── Annex №18 — Wine turnover notification ───────────────────
  {
    id: 'annex_18_wine_turnover_notification',
    annexNumber: 18,
    titleKa: 'შეტყობინება ღვინის კომპანიაში ღვინის ბრუნვის შესახებ',
    titleEn: 'Notification about wine turnover in the company',
    category: 'notification',
    orientation: 'landscape',
    version: VERSION,
    sourceDoc: SOURCE,
    filters: ['dateRange'],
    dataSource: 'wineTurnover',
    headerFields: [...companyHeader],
    columns: [
      { key: 'wineName', headerKa: 'ღვინის დასახელება', headerEn: 'Wine name' },
      { key: 'typeColor', headerKa: 'ტიპი და ფერი', headerEn: 'Type and colour' },
      { key: 'vintage', headerKa: 'მოსავლის წელი', headerEn: 'Vintage' },
      { key: 'openBalance', headerKa: 'ნაშთი პერიოდის დასაწყისში', headerEn: 'Opening balance', numeric: true },
      { key: 'inOwn', headerKa: 'საკუთარი წარმოებიდან', headerEn: 'Own production', group: 'შემოსავალი', groupEn: 'Incoming', numeric: true, total: true },
      { key: 'inBought', headerKa: 'შეძენილი', headerEn: 'Purchased', group: 'შემოსავალი', groupEn: 'Incoming', numeric: true, total: true },
      { key: 'outExport', headerKa: 'რეალიზაცია — ექსპორტი', headerEn: 'Sales — export', group: 'გასავალი', groupEn: 'Outgoing', numeric: true, total: true },
      { key: 'outDomestic', headerKa: 'რეალიზაცია — შიდა ბაზარი', headerEn: 'Sales — domestic', group: 'გასავალი', groupEn: 'Outgoing', numeric: true, total: true },
      { key: 'outBlend', headerKa: 'კუპაჟი', headerEn: 'Blending', group: 'გასავალი', groupEn: 'Outgoing', numeric: true, total: true },
      { key: 'outCategory', headerKa: 'კატეგორიის შეცვლა', headerEn: 'Category change', group: 'გასავალი', groupEn: 'Outgoing', numeric: true, total: true },
      { key: 'outDistill', headerKa: 'გამოხდა', headerEn: 'Distillation', group: 'გასავალი', groupEn: 'Outgoing', numeric: true, total: true },
      { key: 'closeBalance', headerKa: 'ნაშთი პერიოდის ბოლოს', headerEn: 'Closing balance', numeric: true },
    ],
    totals: ['inOwn', 'inBought', 'outExport', 'outDomestic', 'outBlend', 'outCategory', 'outDistill'],
    signatureLabelKa: 'ხელმომწერი პირი:',
    filenameSlug: 'wine_turnover_notification',
  },

  // ────────────── Annex №19 — Distillate/spirit notification ─────────────────
  {
    id: 'annex_19_distillate_notification',
    annexNumber: 19,
    titleKa: 'შეტყობინება ღვინის დისტილატის, ჭაჭის დისტილატის და ყურძნისეული წარმოშობის სპირტის ბრუნვისა და ნაშთების შესახებ',
    titleEn: 'Notification on distillate / pomace distillate / grape spirit turnover and balances',
    category: 'notification',
    orientation: 'landscape',
    version: VERSION,
    sourceDoc: SOURCE,
    filters: ['dateRange'],
    dataSource: '',
    headerFields: [...companyHeader],
    columns: [
      { key: 'name', headerKa: 'დასახელება', headerEn: 'Name' },
      { key: 'age', headerKa: 'ასაკი წელი', headerEn: 'Age (years)' },
      { key: 'openDal', headerKa: 'დალ', headerEn: 'dal', group: 'ნაშთი 01.01', groupEn: 'Opening 01.01', numeric: true },
      { key: 'openAa', headerKa: 'ა.ა.', headerEn: 'a.a.', group: 'ნაშთი 01.01', groupEn: 'Opening 01.01', numeric: true },
      { key: 'inOwn', headerKa: 'საკუთარი წარმოებიდან', headerEn: 'Own production', group: 'შემოსავალი', groupEn: 'Incoming', numeric: true, total: true },
      { key: 'inImport', headerKa: 'იმპორტირებული', headerEn: 'Imported', group: 'შემოსავალი', groupEn: 'Incoming', numeric: true, total: true },
      { key: 'inLocal', headerKa: 'ადგილზე შეძენილი', headerEn: 'Locally purchased', group: 'შემოსავალი', groupEn: 'Incoming', numeric: true, total: true },
      { key: 'outBlend', headerKa: 'გაიხარჯა კუპაჟში', headerEn: 'Used in blending', group: 'გასავალი', groupEn: 'Outgoing', numeric: true, total: true },
      { key: 'outSold', headerKa: 'რეალიზებული', headerEn: 'Sold', group: 'გასავალი', groupEn: 'Outgoing', numeric: true, total: true },
      { key: 'outOther', headerKa: 'სხვა (მიეთითოს)', headerEn: 'Other (specify)', group: 'გასავალი', groupEn: 'Outgoing', numeric: true, total: true },
      { key: 'closeDal', headerKa: 'დალ', headerEn: 'dal', group: 'ნაშთი', groupEn: 'Closing', numeric: true },
      { key: 'closeAa', headerKa: 'ა.ა.', headerEn: 'a.a.', group: 'ნაშთი', groupEn: 'Closing', numeric: true },
    ],
    totals: ['inOwn', 'inImport', 'inLocal', 'outBlend', 'outSold', 'outOther'],
    signatureLabelKa: 'ხელმომწერი პირი:',
    filenameSlug: 'distillate_notification',
    notes: 'აპლიკაცია ჯერ არ აღრიცხავს დისტილატებს — ცარიელი/TODO.',
  },

  // ──────────────── Annex №20 — Brandy/spirits notification ──────────────────
  {
    id: 'annex_20_brandy_notification',
    annexNumber: 20,
    titleKa: 'შეტყობინება ბრენდის, ჭაჭის არყის და მაგარი სასმელის ბრუნვისა და ნაშთების შესახებ',
    titleEn: 'Notification on brandy / pomace vodka / strong beverage turnover and balances',
    category: 'notification',
    orientation: 'landscape',
    version: VERSION,
    sourceDoc: SOURCE,
    filters: ['dateRange'],
    dataSource: '',
    headerFields: [...companyHeader],
    columns: [
      { key: 'name', headerKa: 'დასახელება', headerEn: 'Name' },
      { key: 'age', headerKa: 'ასაკი წელი', headerEn: 'Age (years)' },
      { key: 'openDal', headerKa: 'დალ', headerEn: 'dal', group: 'ნაშთი 01.01', groupEn: 'Opening 01.01', numeric: true },
      { key: 'openAa', headerKa: 'ა.ა.', headerEn: 'a.a.', group: 'ნაშთი 01.01', groupEn: 'Opening 01.01', numeric: true },
      { key: 'inOwn', headerKa: 'საკუთარი წარმოებიდან', headerEn: 'Own production', group: 'შემოსავალი', groupEn: 'Incoming', numeric: true, total: true },
      { key: 'inBought', headerKa: 'შეძენილი', headerEn: 'Purchased', group: 'შემოსავალი', groupEn: 'Incoming', numeric: true, total: true },
      { key: 'outExport', headerKa: 'რეალიზებული — ექსპორტი', headerEn: 'Sold — export', group: 'გასავალი', groupEn: 'Outgoing', numeric: true, total: true },
      { key: 'outDomestic', headerKa: 'რეალიზებული — შიდა ბაზარი', headerEn: 'Sold — domestic', group: 'გასავალი', groupEn: 'Outgoing', numeric: true, total: true },
      { key: 'outOther', headerKa: 'სხვა', headerEn: 'Other', group: 'გასავალი', groupEn: 'Outgoing', numeric: true, total: true },
      { key: 'closeDal', headerKa: 'დალ', headerEn: 'dal', group: 'ნაშთი', groupEn: 'Closing', numeric: true },
      { key: 'closeAa', headerKa: 'ა.ა.', headerEn: 'a.a.', group: 'ნაშთი', groupEn: 'Closing', numeric: true },
    ],
    totals: ['inOwn', 'inBought', 'outExport', 'outDomestic', 'outOther'],
    signatureLabelKa: 'ხელმომწერი პირი:',
    filenameSlug: 'brandy_notification',
    notes: 'აპლიკაცია ჯერ არ აღრიცხავს მაგარ სასმელებს — ცარიელი/TODO.',
  },
];

export const FORM_BY_ID: Record<string, FormTemplate> =
  Object.fromEntries(FORM_TEMPLATES.map(f => [f.id, f]));

export function getTemplate(id: string): FormTemplate | undefined {
  return FORM_BY_ID[id];
}
