const TENANT_CACHE_KEYS = [
  'cf_vessels',
  'cf_lots',
  'cf_fermlogs',
  'cf_lablogs',
  'cf_inventory',
  'cf_tasks',
  'cf_notes',
  'vinea_blocks',
  'vinea_projects',
  'vinea_phenology',
  'vinea_sprays',
  'vinea_scoutings',
  'vinea_soil',
  'vinea_samplings',
  'vinea_harvests',
  'vinea_irrigation',
  'vinea_fertilizer',
  'vinea_audit_logs',
  'cf_bottling_history',
  'cf_transfers_history',
  'cf_grape_intakes',
  'cf_cellar_ops',
  'cf_cost_entries',
  'cf_wine_pricing',
  'cf_storage_locations',
  'cf_storage_movements',
  'cf_sales_dispatches',
  'cf_sales_orders',
  'cf_supplier_payments',
  'cf_certification_records',
  'cf_attachments',
  'cf_crm_leads',
  'cf_ai_drafts',
  'vinea_company_profile',
  'vinea_last_sync_at',
] as const;

export function clearTenantCachedData(storage: Pick<Storage, 'removeItem'>): void {
  TENANT_CACHE_KEYS.forEach(key => storage.removeItem(key));
}
